title: Adam Morgan
description: ""
author: Adam Morgan
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akhmorgan.github.io"
github_username: akhmorgan
linkedin_username: adam-morgan-am
disqus:
  shortname: akhmorgan-github-io
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
excerpt_separator: <!--excerpt-->
show_excerpts: false
sass:
  sass_dir: styles
defaults:
  - scope:
      path: "*"
      type: "posts"
    values:
      layout: "post"
      author: "Adam Morgan"
      comments: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
